color: null
description: null
fieldLayouts:
  b7028d17-fa50-4ae5-95f3-5f4926dca3dd:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-07-07T15:21:51+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 5c8228fd-b7e4-4fa8-b9dd-2a5389c4bb6c # Homepage Hero
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4079ed96-3fbc-4f04-a3a4-c69a56d8c78c
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-07-08T07:49:01+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 3b68cd98-cd43-4ae2-8d02-61222bda35ba # Virtues Section
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: acb75e30-fc47-4ddb-9c6d-7f781527821e
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-07-08T08:45:50+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 0f026b4b-1c4d-43fd-9071-50babbe0d30d # Services Section
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ddc8f3ec-3a3d-4a4f-9f67-8d7234288758
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-07-08T09:31:03+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: c969543d-de4c-4d09-9576-8758dc27afd1 # Testimonials Section
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2bc04907-653c-4668-bc77-31d8bee25f29
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-07-08T10:04:31+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: b79b4e43-e6c0-4c44-9a15-f07ccdaa5d37 # Products Section
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9c76ee4b-50f8-46af-918e-f0686e702433
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-07-08T11:04:41+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: b2608e5b-6a78-41bb-b819-04900f98ce1a # Social Section
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2e511d6c-25b5-4859-b10e-b001e6d3ac7d
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 4a70bf05-8c61-48b3-a2a8-8032d03a2fb4
        userCondition: null
handle: ent_homepage
hasTitleField: false
icon: null
name: Homepage
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: 'The Leading Edge - Hair and Beauty'
titleTranslationKeyFormat: null
titleTranslationMethod: site
