color: null
description: null
fieldLayouts:
  60197930-b747-4177-917b-3efd70103a22:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-07-14T16:08:04+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 75d5ff91-e0e7-479a-b047-041d2c3e1649 # Page Header
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d435c510-f4f1-49ad-9112-e242d5694577
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-07-15T09:08:14+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 10dcb136-b8a7-4325-90fe-c0cda2e1ebd1 # Simple Text
            handle: introText
            includeInCards: false
            instructions: null
            label: 'Intro Text'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2d07b64d-7f70-4409-a72d-f081fc5558f4
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-07-14T16:30:00+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 35f4bfc2-4432-43df-bd81-7ccfd0e7a7f1 # Team
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1ef19276-c2cc-43a9-9847-1d1c0936c154
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-07-14T16:17:02+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 3b68cd98-cd43-4ae2-8d02-61222bda35ba # Cards Section
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e6a07425-3ec8-48bf-abdc-a6377b0b3681
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-07-14T16:21:59+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 71202746-fb78-4408-b9b3-1c3d1e39ffb8 # Call to Action
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: faf9b527-52c8-4f90-adda-dc24a3891cb2
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 41803200-bfdd-4e88-b1a2-015f4ebead49
        userCondition: null
handle: page_ent_team
hasTitleField: false
icon: null
name: Team
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: '{cb_pageHeader.pageTitle}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
