color: amber
description: null
fieldLayouts:
  308b815f-75b8-46fb-9899-5be7547bea55:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-07-14T09:28:34+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 54ad6db4-d4f1-442d-b6c6-c1b6ac754cf9 # Straight Text
            handle: subTitle
            includeInCards: false
            instructions: null
            label: Title
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e60bf9d0-9e7b-4f92-a18b-64a79b9c3876
            userCondition: null
            warning: null
            width: 75
          -
            dateAdded: '2025-07-14T09:28:34+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 54ad6db4-d4f1-442d-b6c6-c1b6ac754cf9 # Straight Text
            handle: subTabText
            includeInCards: true
            instructions: null
            label: 'Tab Text'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f7275249-03b7-462d-b8ad-01555bb08752
            userCondition: null
            warning: null
            width: 25
          -
            dateAdded: '2025-07-14T09:38:13+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: b42073cc-57b6-4636-b08c-5b9bb29facb4 # Sub Service Intro
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ddb09388-4afd-403f-92f0-b595c6deb0a2
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-07-14T10:00:42+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: d2c3b28c-ed81-4d1d-a2c8-8a4cfff51ecd # Price List
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 317bed0c-73f6-45eb-bf67-8560515a8511
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 86305096-8796-43f1-8285-be75e4e63efc
        userCondition: null
handle: subServices3
hasTitleField: false
icon: null
name: 'Sub Services'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
