altTranslationKeyFormat: null
altTranslationMethod: none
fieldLayouts:
  fd17daef-cee2-45bc-826b-9472e321015a:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-07-07T15:05:58+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: 2e3b9d39-2ace-4d91-b874-c8ba4657178b
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 957300c4-65f6-4665-a561-5556bc6013f1
        userCondition: null
fs: assets
handle: assets
name: Assets
sortOrder: 1
subpath: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: ''
transformSubpath: ''
