columnSuffix: null
handle: individualService
instructions: null
name: 'Individual Service'
searchable: false
settings:
  fieldLayouts:
    __assoc__:
      -
        - 5dcd32b9-2f0d-4a07-8a66-e138aaf8627e
        -
          __assoc__:
            0:
              - tabs
              -
                -
                  __assoc__:
                    0:
                      - name
                      - Content
                    1:
                      - uid
                      - 09a2ae3c-5ba1-4404-a577-33e7b7e1069a
                    4:
                      - elements
                      -
                        -
                          __assoc__:
                            0:
                              - type
                              - craft\fieldlayoutelements\CustomField
                            1:
                              - handle
                              - serviceTitle
                            2:
                              - label
                              - 'Service Title'
                            6:
                              - required
                              - false
                            7:
                              - providesThumbs
                              - false
                            8:
                              - includeInCards
                              - false
                            9:
                              - width
                              - 50
                            10:
                              - dateAdded
                              - '2025-07-14T09:11:11+00:00'
                            11:
                              - uid
                              - dd00f21b-4d42-454d-9583-6324907be197
                            14:
                              - fieldUid
                              - 54ad6db4-d4f1-442d-b6c6-c1b6ac754cf9 # Straight Text
                        -
                          __assoc__:
                            0:
                              - type
                              - craft\fieldlayoutelements\CustomField
                            1:
                              - handle
                              - tabTitle
                            2:
                              - label
                              - 'Tab Title'
                            6:
                              - required
                              - false
                            7:
                              - providesThumbs
                              - false
                            8:
                              - includeInCards
                              - false
                            9:
                              - width
                              - 50
                            10:
                              - dateAdded
                              - '2025-07-14T09:11:11+00:00'
                            11:
                              - uid
                              - 4c57845a-b339-4313-a8a4-3fdd8cff4ec4
                            14:
                              - fieldUid
                              - 54ad6db4-d4f1-442d-b6c6-c1b6ac754cf9 # Straight Text
            3:
              - cardThumbAlignment
              - end
  viewMode: grouped
translationKeyFormat: null
translationMethod: site
type: craft\fields\ContentBlock
