columnSuffix: null
handle: requirements
instructions: null
name: Requirements
searchable: false
settings:
  addRowLabel: 'Add a Requirement'
  columns:
    __assoc__:
      -
        - col1
        -
          __assoc__:
            -
              - heading
              - Requirement
            -
              - handle
              - requirement
            -
              - width
              - ''
            -
              - type
              - singleline
  defaults:
    -
      __assoc__:
        -
          - col1
          - ''
  maxRows: null
  minRows: null
  staticRows: false
translationKeyFormat: null
translationMethod: none
type: craft\fields\Table
