columnSuffix: null
handle: responsibilities
instructions: null
name: Responsibilities
searchable: false
settings:
  addRowLabel: 'Add a Responsibility'
  columns:
    __assoc__:
      -
        - col1
        -
          __assoc__:
            -
              - heading
              - Responsibility
            -
              - handle
              - responsibility
            -
              - width
              - ''
            -
              - type
              - singleline
  defaults:
    -
      __assoc__:
        -
          - col1
          - ''
  maxRows: null
  minRows: null
  staticRows: false
translationKeyFormat: null
translationMethod: none
type: craft\fields\Table
