columnSuffix: null
handle: testimonials
instructions: null
name: Testimonials
searchable: false
settings:
  createButtonLabel: 'Add a Testimonial'
  defaultIndexViewMode: cards
  enableVersioning: false
  entryTypes:
    -
      __assoc__:
        -
          - uid
          - 224318bf-f739-48f8-b570-dc4deefe6f0e # Testimonials
        -
          - group
          - General
  includeTableView: false
  maxEntries: null
  minEntries: null
  pageSize: 50
  propagationKeyFormat: null
  propagationMethod: all
  showCardsInGrid: true
  viewMode: cards
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
