dateModified: 1752055013
email:
  fromEmail: access@hypha.media
  fromName: TLE-2025
  transportType: craft\mail\transportadapters\Sendmail
fs:
  assets:
    hasUrls: true
    name: Assets
    settings:
      path: assets
    type: craft\fs\Local
    url: /assets
graphql:
  publicToken:
    enabled: false
    expiryDate: null
meta:
  __names__:
    0f026b4b-1c4d-43fd-9071-50babbe0d30d: 'Services Section' # Services Section
    3b68cd98-cd43-4ae2-8d02-61222bda35ba: 'Cards Section' # Cards Section
    3e7a3e99-ba2f-44b4-966e-e6783dd7e3c1: 'Hero Buttons' # Hero Buttons
    04ddff7f-52ed-458a-bc0c-a3a9d4b76f4d: 'Single Image' # Single Image
    4ed1b04a-6530-4a34-874c-c5f29f911e66: 'Four Images' # Four Images
    5c8228fd-b7e4-4fa8-b9dd-2a5389c4bb6c: 'Homepage Hero' # Homepage Hero
    5d6f4599-0482-49dc-b4e6-eb7db8af869d: 'Basic with H2' # Basic with H2
    9ab1b041-ae5f-451c-aa7a-e7dda1e2d1f9: 'Title Field' # Title Field
    9b42751e-b87f-4957-8c54-5a457d443a7f: 'Basic with H2' # Basic with H2
    21f4ef74-64dc-48e3-bb94-93d62c25ef08: TLE-2025 # TLE-2025
    30d70629-c8e5-40db-9f27-dd7dd53d0afb: 'Card Link' # Card Link
    45b3edbc-893f-4d31-acaa-4f187ee99099: Cards # Cards
    48ff7023-466f-423c-a293-c4ebec9ab0a4: Testimonials # Testimonials
    54ad6db4-d4f1-442d-b6c6-c1b6ac754cf9: 'Straight Text' # Straight Text
    54b32803-64e0-46aa-bacf-ecddf2f5db7a: 'Section Link' # Section Link
    70cbf51f-c6a4-4501-ab10-6544b0adb9fd: Simple # Simple
    75d5ff91-e0e7-479a-b047-041d2c3e1649: 'Page Header' # Page Header
    223fbc1e-4eb0-4383-82ba-1041ce5b1e00: Homepage # Homepage
    392d336a-d1e6-4233-89d7-cf232f91adb8: 'Bold and Italic' # Bold and Italic
    678e5f0a-719b-48e9-85b7-506679f364f5: Homepage # Homepage
    9832c994-1873-429f-b552-652988c0558b: Salon # Salon
    046080fc-7aad-4c07-b0fa-b55961a0f0de: Salon # Salon
    224318bf-f739-48f8-b570-dc4deefe6f0e: Testimonials # Testimonials
    26138429-fcf3-4e89-a520-7bfdbd1591ee: Assets # Assets
    43665714-2299-44fa-abf3-97b45c8a12c7: 'Services Cards' # Services Cards
    b79b4e43-e6c0-4c44-9a15-f07ccdaa5d37: 'Products Section' # Products Section
    b2608e5b-6a78-41bb-b819-04900f98ce1a: 'Social Section' # Social Section
    b5144bca-43e4-4a75-8d36-4405e3f2629a: 'Testimonial Text' # Testimonial Text
    c4bebee5-c1d4-47bf-be47-8bcfeb2783ec: 'Services Cards' # Services Cards
    c969543d-de4c-4d09-9576-8758dc27afd1: 'Testimonials Section' # Testimonials Section
    d51d5a9b-69fe-4e13-acd6-d4f9a20ccae1: 'Title Text' # Title Text
    d9707244-1d4e-4b5b-9d06-b6055492603e: TLE-2025 # TLE-2025
    eb143e66-f41e-413f-aaff-b1cc34d3e545: 'Simple Cards' # Simple Cards
    f0eb6556-1429-4336-86ff-322eb5be4254: 'Intro Section' # Intro Section
    f117f59d-5600-46e1-8a81-3dec61d0f0c9: 'Six Images' # Six Images
plugins:
  ckeditor:
    edition: standard
    enabled: true
    schemaVersion: 3.0.0.0
  craftagram:
    edition: standard
    enabled: true
    licenseKey: ZS0B937I20MS4FWRH0VQJ6F2
    schemaVersion: 3.0.0
  field-manager:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
system:
  edition: solo
  live: true
  name: TLE-2025
  schemaVersion: 5.8.0.3
  timeZone: America/Los_Angeles
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: null
  photoVolumeUid: null
  require2fa: false
  requireEmailVerification: true
