dateModified: 1752570494
elementSources:
  craft\elements\Entry:
    -
      key: '*'
      type: native
    -
      key: singles
      type: native
    -
      heading: Structures
      key: 'heading:5ed19833-d0be-413d-b83f-739235094aeb'
      type: heading
    -
      defaultSort:
        - structure
        - asc
      defaultViewMode: ''
      disabled: false
      key: 'section:d60136f4-9baf-4f3c-9a20-bbd1bf47b28a' # Services
      tableAttributes:
        - status
      type: native
email:
  fromEmail: access@hypha.media
  fromName: TLE-2025
  transportType: craft\mail\transportadapters\Sendmail
fs:
  assets:
    hasUrls: true
    name: Assets
    settings:
      path: assets
    type: craft\fs\Local
    url: /assets
graphql:
  publicToken:
    enabled: false
    expiryDate: null
meta:
  __names__:
    0f026b4b-1c4d-43fd-9071-50babbe0d30d: 'Services Section' # Services Section
    3b0f3bfb-1b7f-4be0-94f0-0a2f29509f4f: Team # Team
    3b68cd98-cd43-4ae2-8d02-61222bda35ba: 'Cards Section' # Cards Section
    3e7a3e99-ba2f-44b4-966e-e6783dd7e3c1: 'Hero Buttons' # Hero Buttons
    04ddff7f-52ed-458a-bc0c-a3a9d4b76f4d: 'Single Image' # Single Image
    4ed1b04a-6530-4a34-874c-c5f29f911e66: 'Four Images' # Four Images
    5c8228fd-b7e4-4fa8-b9dd-2a5389c4bb6c: 'Homepage Hero' # Homepage Hero
    5d6f4599-0482-49dc-b4e6-eb7db8af869d: 'Basic with H2' # Basic with H2
    8dc06e17-b136-4714-997a-6b1f293e9c41: 'Bold, Italic and Link' # Bold, Italic and Link
    9ab1b041-ae5f-451c-aa7a-e7dda1e2d1f9: 'Title Field' # Title Field
    9b42751e-b87f-4957-8c54-5a457d443a7f: 'Basic with H2' # Basic with H2
    10dcb136-b8a7-4325-90fe-c0cda2e1ebd1: 'Simple Text' # Simple Text
    21f4ef74-64dc-48e3-bb94-93d62c25ef08: TLE-2025 # TLE-2025
    30d70629-c8e5-40db-9f27-dd7dd53d0afb: 'Card Link' # Card Link
    35f4bfc2-4432-43df-bd81-7ccfd0e7a7f1: Team # Team
    45b3edbc-893f-4d31-acaa-4f187ee99099: Cards # Cards
    48ff7023-466f-423c-a293-c4ebec9ab0a4: Testimonials # Testimonials
    54ad6db4-d4f1-442d-b6c6-c1b6ac754cf9: 'Straight Text' # Straight Text
    54b32803-64e0-46aa-bacf-ecddf2f5db7a: 'Section Link' # Section Link
    70cbf51f-c6a4-4501-ab10-6544b0adb9fd: Simple # Simple
    75d5ff91-e0e7-479a-b047-041d2c3e1649: 'Page Header' # Page Header
    91bf7b22-c506-4a80-8c0d-506bf77a3dfc: 'Sub Services' # Sub Services
    223fbc1e-4eb0-4383-82ba-1041ce5b1e00: Homepage # Homepage
    392d336a-d1e6-4233-89d7-cf232f91adb8: 'Bold and Italic' # Bold and Italic
    678e5f0a-719b-48e9-85b7-506679f364f5: Homepage # Homepage
    3815c76e-4a12-40f8-8dd1-9568da8fdf25: Team # Team
    9832c994-1873-429f-b552-652988c0558b: Salon # Salon
    046080fc-7aad-4c07-b0fa-b55961a0f0de: Salon # Salon
    55300cfe-bdf4-4ff4-8cb4-41e6c4d57622: 'Service Type' # Service Type
    224318bf-f739-48f8-b570-dc4deefe6f0e: Testimonials # Testimonials
    5521768b-fe93-4d18-b281-f9a472cf9dca: 'All Services' # All Services
    26138429-fcf3-4e89-a520-7bfdbd1591ee: Assets # Assets
    43665714-2299-44fa-abf3-97b45c8a12c7: 'Services Cards' # Services Cards
    71202746-fb78-4408-b9b3-1c3d1e39ffb8: 'Call to Action' # Call to Action
    a6966eba-abc7-43bd-aad8-95073f426a6d: 'Summary Section' # Summary Section
    b79b4e43-e6c0-4c44-9a15-f07ccdaa5d37: 'Products Section' # Products Section
    b2608e5b-6a78-41bb-b819-04900f98ce1a: 'Social Section' # Social Section
    b5144bca-43e4-4a75-8d36-4405e3f2629a: 'Testimonial Text' # Testimonial Text
    b42073cc-57b6-4636-b08c-5b9bb29facb4: 'Sub Service Intro' # Sub Service Intro
    b3726252-6c72-46e5-b01e-d92574299019: 'Single Button' # Single Button
    bd8fab1a-d105-471a-a842-1dc57f562d2e: 'All Services' # All Services
    c1e5720b-386a-4bba-8784-306bc80ba4f6: Specialities # Specialities
    c4bebee5-c1d4-47bf-be47-8bcfeb2783ec: 'Services Cards' # Services Cards
    c55dc4be-da97-4592-9d58-444951e11eef: Team # Team
    c969543d-de4c-4d09-9576-8758dc27afd1: 'Testimonials Section' # Testimonials Section
    cd54e7f4-5c22-4c1f-97e1-6e017ee1fcc6: 'Sub Service' # Sub Service
    d2c3b28c-ed81-4d1d-a2c8-8a4cfff51ecd: 'Price List' # Price List
    d51d5a9b-69fe-4e13-acd6-d4f9a20ccae1: 'Title Text' # Title Text
    d60136f4-9baf-4f3c-9a20-bbd1bf47b28a: Services # Services
    d9707244-1d4e-4b5b-9d06-b6055492603e: TLE-2025 # TLE-2025
    e21536ab-798f-4de7-9666-70903d331159: Services # Services
    eb38d150-0774-403c-8be3-6b8c480c6f8e: Specialities # Specialities
    eb143e66-f41e-413f-aaff-b1cc34d3e545: 'Simple Cards' # Simple Cards
    f0eb6556-1429-4336-86ff-322eb5be4254: 'Intro Section' # Intro Section
    f117f59d-5600-46e1-8a81-3dec61d0f0c9: 'Six Images' # Six Images
plugins:
  ckeditor:
    edition: standard
    enabled: true
    schemaVersion: 3.0.0.0
  craftagram:
    edition: standard
    enabled: true
    licenseKey: ZS0B937I20MS4FWRH0VQJ6F2
    schemaVersion: 3.0.0
  field-manager:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
system:
  edition: solo
  live: true
  name: TLE-2025
  schemaVersion: 5.8.0.3
  timeZone: America/Los_Angeles
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: null
  photoVolumeUid: null
  require2fa: false
  requireEmailVerification: true
